apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: supplychainsc
provisioner: kubernetes.io/storageos
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  pool: default
  description: Kubernetes volume
  fsType: ext4
  adminSecretNamespace: default
  adminSecretName: storageos-secret
