kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: supplychainsc
provisioner: k8s.io/local-path-storage
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  encrypted: "true"
